# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Ejecutar aplicación
      run: |
        # Comandos para ejecutar tu aplicación
        # Ejemplo genérico:
        echo "Ejecutando la aplicación..."
        python main.py || exit 1
        echo "Aplicación ejecutada correctamente"